OTPL-7842 Migrate parent to `basepom-minimal` directly
opentable/otj-version-exposure-maven-plugin pull request #4
Opened 2023-09-06 05:17 UTC by dkaukov

inline OSS settings

2023-09-06 05:18 UTC, dkaukov commented on src/main/java/com/opentable/RuntimeMojoExecutionException.java
> +        this.mojoExecutionException = new MojoExecutionException(mojoExecutionException);
findbugs

2023-09-06 05:18 UTC, dkaukov commented on src/main/java/com/opentable/RuntimeMojoExecutionException.java
> +        return new MojoExecutionException(mojoExecutionException);
findbugs

2023-09-06 15:01 UTC, mikebell90 requested changes
please compare to otj-pg-embedded pr (which you have not reviewed btw) - these don't look that consistent

2023-09-07 19:24 UTC, mikebell90 approved these changes
This is fine but **PLEASE compare to otj-pg-embedded and review that PR too**

2023-09-12 00:22 UTC, merged